# Generated by Django 5.2.3 on 2025-06-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feira_expositores_aprovados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feira',
            name='expositores',
        ),
    ]
