# Generated by Django 5.2.3 on 2025-06-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_feira_expositores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feira',
            name='organizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feiras_organizadas', to='core.organizador'),
        ),
    ]
